title: "Taregh Magham"
url: "https://tmagham.me"
baseurl: ""
username: tmagham
author: tmagham
twitter_username: 
profile_picture: /images/profile.jpeg

markdown: kramdown
excerpt_separator: <!--more-->
highlighter: rouge
paginate: 8
paginate_path: "/notes/page:num/"

plugins: [rouge,kramdown,jekyll-paginate]

footer: yes

nav:
  - name: "about"
    link: "/"
  - name: "cv.pdf"
    link: "/assets/tmagham.pdf"
  - name: "contact"
    link: "/contact"

social:
  - name: linkedin/tmagham
    icon: ri-linkedin-box-line
    url: https://www.linkedin.com/in/tmagham/
  - name: github/tmagham
    icon: ri-github-line
    url: https://github.com/t-magham
  - name: gitlab/tmagham
    icon: ri-gitlab-line
    url: https://gitlab.com/tmagham

academic:

